/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\alien_glass_material_test.glb 
Author: 3Dee (https://sketchfab.com/mellydeeis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-glass-material-test-33b3c4ab44f94195ae2c4141d8978888
Title: Alien Glass Material Test
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelX(props) {
  const { nodes, materials } = useGLTF('/alien_glass_material_test.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Material-material'].geometry} material={materials.Material} position={[0.017, 0.09, -0.015]} />
        <mesh geometry={nodes['Material_002-material'].geometry} material={materials['Material.002']} position={[0.017, 0.019, -0.015]} />
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.001']} position={[0.017, 0.197, -0.015]} />
      </group>
    </group>
  )
}

useGLTF.preload('/alien_glass_material_test.glb')
